inf = input('Digite algo: ')
print(inf)
print(type(inf))
print('É Alfabético? ', inf.isalpha())
print('É Numérico? ', inf.isnumeric())
print('É Alfanumérico? ', inf.isalnum())
print('Está em Maiúscula? ', inf.isupper())
print('Está em Minúscula ', inf.islower())
print('É ASCII? ', inf.isascii())
print('É um dígito? ', inf.isdigit())
print('É decimal? ', inf.isdecimal())
print('É Idenfificador? ', inf.isidentifier())
print('É Espaço? ', inf.isspace())
